services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otw-puzzli-authentication-api
    ports:
      - "5010:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Swagger__Enabled=true
      - Database__MigrateOnStartup=true
      - BootstrapAdmin__Enabled=${BOOTSTRAP_ADMIN_ENABLED:-false}
      - BootstrapAdmin__Email=${BOOTSTRAP_ADMIN_EMAIL:-}
      - BootstrapAdmin__Name=${BOOTSTRAP_ADMIN_NAME:-Administrador}
      - BootstrapAdmin__Username=${BOOTSTRAP_ADMIN_USERNAME:-admin}
      - BootstrapAdmin__CompanyId=${BOOTSTRAP_ADMIN_COMPANY_ID:-c12dd532-481b-4ff2-a4f1-a1b2ee417f75}
    networks:
      - puzzli-network

networks:
  puzzli-network:
    driver: bridge
